name: Push, PR with conditional

env:
  RENDER_HOST_URL: "https://test-portal-master-pr-${{github.event.number}}.onrender.com"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - name: Wait a second...
        run: sleep 1
        
  build:
    needs: test1
    name: Output result and execute script
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip_manage_origins')"
    steps:
      - uses: actions/checkout@v2
      - name: Build Render host URL and execute bash script
        run: |
          echo "github.event: ${{ github.event }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.type: ${{ github.event.type }}"
          echo "RENDER_HOST_URL = $RENDER_HOST_URL"
          chmod +x ./deploy/do_something.sh
          ./deploy/do_something.sh add $RENDER_HOST_URL
   
  testForPush:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait a second...
        run: |
          sleep 1
          echo "Test for push event has run"
     
  testForPr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait a second...
        run: |
          sleep 1
          echo "Test for pull_request event has run"
