name: Build URL with PRs number and execute bash script on open PR

env:
  RENDER_HOST_URL: "https://test-portal-master-pr-${{github.event.number}}.onrender.com"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  test:
    name: A test that passes
    runs-on: ubuntu-latest
    steps:
      - name: Wait a second...
        run: sleep 3
        
  build:
    needs: test
    name: Output result and execute script
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip_manage_origins')"
    steps:
      - name: Build Render host URL and execute bash script
        run: |
          echo "RENDER_HOST_URL = $RENDER_HOST_URL"
          chmod +x ./deploy/do-something.sh
          ./deploy/do-something.sh add $RENDER_HOST_URL
          
