name: Print PR number on open PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

env:
  RENDER_SERVICE_NAME: "test-portal-master"
  RENDER_HOST_URL: "https://${RENDER_SERVICE_NAME}-pr-${{github.event.number}}.onrender.com"

jobs:
  build:
    name: Test built Render host
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip_manage_origins')"
    steps:
      - name: Build Render host URL
        run: |
          BUILT_HOST="https://${RENDER_SERVICE_NAME}-pr-${{github.event.number}}.onrender.com"
          echo $BUILT_HOST
          echo $RENDER_HOST_URL
          
