name: Print PR number on open PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

env:
  RENDER_SERVICE_NAME: "charity-portal-master"

jobs:
  build:
    name: Add Auth0 origins
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip_manage_origins')"
    steps:
      - name: pr-number-action
        id: pr-number-action
        uses: kkak10/pr-number-action@v1.3
        with:
          # The GitHub token used to create an authenticated client.
          github-token: ${{github.token}}

#       - name: Get PR number
#         uses: actions/github-script@0.3.0
#         with:
#           github-token: ${{github.token}}
#           script: |
#             const core = require('@actions/core')
#             const prNumber = context.payload.number;
#             core.exportVariable('PULL_NUMBER', prNumber);
#       - uses: actions/checkout@v2

      - name: Add render.com preview host to Auth0 origin
        run: |
          echo ${{steps.pr-number-action.outputs.pr}}
          BUILT_HOST="https://${RENDER_SERVICE_NAME}-pr-${{steps.pr-number-action.outputs.pr}}.onrender.com"
          echo $BUILT_HOST
          
